name: MX
version: '5.0 (Dominus Deus)'
api-version: '1.13'
author: pawsashatoy
description: "Complex combat/automation analysis anti-cheat"
main: kireiko.dev.anticheat.MX
depend: [ ProtocolLib ]
commands:
  mx:
    description: "Main command"
    usage: "/mx"
    permission: "mx.admin"
    aliases: [ mx ]
