name: MX
version: '5.4 (Requin)'
api-version: '1.13'
author: pawsashatoy, Vagdedes, _The_Lord_, Loyisa, Dg32z, Bratif, ptrcall, yatwinkle, DanFM, Vladyaso, gamemax
description: "Complex combat/automation ML analysis anti-cheat (ML: quark-e-4.0-100k-mini)"
main: kireiko.dev.anticheat.MX
depend: [ ProtocolLib ]
commands:
  mx:
    description: "Main command"
    usage: "/mx"
    permission: "mx.admin"
    aliases: [ mx ]
